### ISSUE TITLE
What code style is that?

### ISSUE THREAD

**Issue by oliversalzburg** [ZacWolf/jquery.ui.windoge#1]
That indentation looks very creative. Is there a logic behind it?

**Comment by ZacWolf** [comment]
Sorry, I didn't get notified of this. Honestly it's a coding style that I've used since my days of Fortran. A tab being a single byte, vs 2-4 spaces, being 2-4 bytes added to your code.

I also align all variables when possible so they are easy to spot when a variable value is assigned, changed, etc., with "typing" done on the far right so you can easy track when a new variable is initialized.

At this point, I implement this style without even thinking.
